security:
  oauth2:
    client:
      client-id: lssClient
      client-secret: lssSecret
      access-token-uri: https://auth-server-ps.cfapps.io/oauth/token
      user-authorization-uri: https://auth-server-ps.cfapps.io/oauth/authorize
      scope: read, write
      grant-type: authorization_code
      use-current-uri: true

resource:
  server:
    uri: https://resource-server-ps.cfapps.io/api/users